[project]
name = "classindownloader"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "loguru>=0.7.3",
    "lxml>=6.0.2",
    "requests>=2.32.5",
    "selenium>=4.40.0",
    "tqdm>=4.67.1",
]
